#!/usr/bin/ruby

class Fixnum
  def divides p
    self % p == 0
  end
end

n = File.read(ARGV.first).to_i

(1..n).each do |i|
  if i.divides 15
    puts "Hop" 
  else
    puts "Hoppity" if i.divides 3
    puts "Hophop" if i.divides 5
  end
end
